An error occurred while executing the following cell:
------------------
# Plots Sigmoid vs. Probit.


import numpy as np
import matplotlib.pyplot as plt

try:
    import pyprobml_utils as pml
except ModuleNotFoundError:
    %pip install pyprobml_utils
    import pyprobml_utils as pml

from scipy.special import expit
from scipy.stats import norm

x = np.arange(-6, 6, 0.1)
l = np.sqrt(np.pi / 8)
plt.plot(x, expit(x), "r-", label="sigmoid")
plt.plot(x, norm.cdf(l * x), "b--", label="probit")

plt.axis([-6, 6, 0, 1])
plt.legend()
pml.savefig("probitSigmoidPlot.pdf")
plt.show()
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_2689/2186615118.py in <module>
      7 try:
----> 8     import pyprobml_utils as pml
      9 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'pyprobml_utils'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_2689/2186615118.py in <module>
      9 except ModuleNotFoundError:
     10     get_ipython().run_line_magic('pip', 'install pyprobml_utils')
---> 11     import pyprobml_utils as pml
     12 
     13 from scipy.special import expit

ModuleNotFoundError: No module named 'pyprobml_utils'
ModuleNotFoundError: No module named 'pyprobml_utils'
